version: 2.1

orbs:
  rj-chatwork: rhems-japan/chatwork@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  # bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0
  rj-package: rhems-japan/package@0.0.27

parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"
  ssh-key:
    type: string
    default: "9c:e3:92:94:43:a2:70:9d:56:76:21:6b:4a:5b:6f:ba"

jobs:
  integration-test-1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - << pipeline.parameters.ssh-key >>
      # - run:
      #     name: add script
      #     command: echo ". ${CI_FUNCTIONS}" >> $BASH_ENV
      # - run:
      #     name: create message
      #     command: create_message
      - run:
          name: create message
          command: |
            MESSAGE=$(cat \<<EOF
            Branch : $CIRCLE_BRANCH
            Time : $(date "+%Y/%m/%d %H:%M:%S")
            https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}
            EOF
            )
            BODY="[preview id=866484042 ht=60][hr]${MESSAGE}"
            echo "export MESSAGE='${BODY}'" >> $BASH_ENV
      - rj-chatwork/chatwork-send:
          room_id: "255694560"
          body: $MESSAGE
      - rj-package/create_badge:
          app: "orbs-chatwork"
      - rj-package/update_readme

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - shellcheck/check:
          dir: ./src/scripts
          exclude: "SC2148, SC2154, SC2155"
      # - bats/run:
      #     path: ./src/tests
      - orb-tools/publish-dev:
          orb-name: rhems-japan/chatwork
          context: orb-publishing
          requires:
            - orb-tools/lint
            - orb-tools/pack
            # - bats/run
            # - shellcheck/check
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-1
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: rhems-japan/chatwork
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - integration-test-1
          filters:
            branches:
              only:
                - main
